resources:
  - name: yahavhook
    type: IncomingWebhook
    configuration:
      webhookName: yahav_hook
    

pipelines: 
  - name: jenkins_yahav
    configuration:
      nodePool: u18dynamic
    steps:
      - name: HelloStep
        type: Bash
        configuration:
          inputResources:
            - name: yahavhook
        execution:
          onExecute:
            - echo "hello"
      - name: JenkinsStep
        type: Jenkins
        configuration:
          jenkinsJobName: rest-pipeline
          inputResources:
              - name: yahavhook
          integrations:
            - name: yahav
          inputSteps:
            - name: HelloStep

